DROP TABLE RESUME_COPY CASCADE CONSTRAINTS;

CREATE TABLE RESUME_COPY (
                             RESUME_ID NUMBER(5),
                             RESUME_TITLE VARCHAR2(3000),
                             NAME VARCHAR2(3000),
                             BIRTHDATE DATE,
                             PHONENUMBER VARCHAR2(3000),
                             EMAIL VARCHAR2(3000),
                             POSTAL_CODE_ID NUMBER(5),
                             ADDRESS VARCHAR2(3000),
                             SELF_INTRODUCTION VARCHAR2(3000),
                             MEMBER_ID NUMBER(5),
                             PROFILE VARCHAR2(3000),
                             CREATE_AT DATE,
                             MODIFIED_AT DATE,
                             IS_PUBLIC NUMBER(1),
                             MATCH_SCORE NUMBER(5),
                             CONSTRAINT PK_RESUME_COPY PRIMARY KEY (RESUME_ID),
                             CONSTRAINT FK_MEMBER_TO_RESUME_COPY FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE

);

-- Resume_Tag
DROP TABLE RESUME_TAG_COPY CASCADE CONSTRAINTS;

CREATE TABLE RESUME_TAG_COPY (
                                 RESUME_TAG_ID NUMBER(5),
                                 RESUME_ID NUMBER(5),
                                 TAG_ID NUMBER(5),
                                 CREATE_AT DATE,
                                 MODIFIED_AT DATE,
                                 CONSTRAINT PK_RESUME_TAG_COPY PRIMARY KEY (RESUME_TAG_ID),
                                 CONSTRAINT FK_RES_TAG_COPY_RESUME FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE,
                                 CONSTRAINT FK_RES_TAG_COPY_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID) ON DELETE CASCADE
);


-- Career
DROP TABLE CAREER_COPY CASCADE CONSTRAINTS;

CREATE TABLE CAREER_COPY (
                             CAREER_ID NUMBER(5),
                             RESUME_ID NUMBER(5),
                             COMPANY_NAME VARCHAR2(3000),
                             DEPARTMENT_NAME VARCHAR2(3000),
                             HIRE_YM DATE,
                             RESIGN_YM DATE,
                             POSITION VARCHAR2(3000),
                             JOB_ID NUMBER(5),
                             JOB_GROUP_ID NUMBER(5),
                             SALARY NUMBER(6),
                             DETAIL VARCHAR2(3000),

                             CONSTRAINT PK_CAREER_COPY PRIMARY KEY (CAREER_ID),
                             CONSTRAINT FK_RESUME_COPY_TO_CAREER_COPY FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE,
                             CONSTRAINT FK_JOB_TO_CAREER_COPY FOREIGN KEY (JOB_ID) REFERENCES JOB(JOB_ID),
                             CONSTRAINT FK_JOB_GROUP_TO_CAREER_COPY FOREIGN KEY (JOB_GROUP_ID) REFERENCES JOB_GROUP(JOB_GROUP_ID)
);



DROP TABLE EDUCATION_COPY CASCADE CONSTRAINTS;

CREATE TABLE EDUCATION_COPY (
                                EDU_ID NUMBER(5),
                                Resume_ID NUMBER(5),
                                EDU_INSTITUTION VARCHAR2(3000),
                                EDU_NAME VARCHAR2(3000),
                                START_DATE DATE,
                                END_DATE DATE,
                                CONTENT VARCHAR2(3000),

                                CONSTRAINT PK_EDU_COPY PRIMARY KEY (EDU_ID),
                                CONSTRAINT FK_EDU_COPY_RESUME FOREIGN KEY (Resume_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);


-- School
DROP TABLE SCHOOL_COPY CASCADE CONSTRAINTS;

CREATE TABLE SCHOOL_COPY (
                             SCHOOL_ID NUMBER(5),
                             RESUME_ID NUMBER(5),
                             SORTATION VARCHAR2(3000),
                             SCHOOL_NAME VARCHAR2(3000),
                             YEAR_OF_GRADUATION VARCHAR2(3000), -- 수정됨 (원본과 동일하게)
                             START_DATE DATE,
                             END_DATE DATE,
                             MAJOR_NAME VARCHAR2(3000),
                             STATUS VARCHAR2(3000),

                             CONSTRAINT PK_SCHOOL_COPY PRIMARY KEY (SCHOOL_ID),
                             CONSTRAINT FK_RESUME_COPY_TO_SCHOOL_COPY FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);

-- Portfolio
DROP TABLE PORTFOLIO_COPY CASCADE CONSTRAINTS;

CREATE TABLE PORTFOLIO_COPY (
                                PORTFOLIO_ID NUMBER(5),
                                RESUME_ID NUMBER(5),
                                FILE_NAME VARCHAR2(3000),
                                STORED_FILE_NAME VARCHAR2(3000),
                                FILE_EXTENSION VARCHAR2(300),
                                CREATE_AT DATE,
                                MODIFIED_AT DATE,

                                CONSTRAINT PK_PORTFOLIO_COPY PRIMARY KEY (PORTFOLIO_ID),
                                CONSTRAINT FK_PORT_COPY_RESUME FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);



DROP TABLE CERTIFICATE_RESUME_COPY CASCADE CONSTRAINTS;

CREATE TABLE CERTIFICATE_RESUME_COPY (
                                         CERTIFICATE_RESUME_ID NUMBER(5),
                                         RESUME_ID        NUMBER(5),
                                         CERTIFICATE_NAME VARCHAR2(3000),
                                         ACQUISITION_DATE DATE,
                                         ISSUING_AUTHORITY VARCHAR2(3000),

                                         CONSTRAINT PK_CERTIFICATE_RESUME_COPY PRIMARY KEY (CERTIFICATE_RESUME_ID),
                                         CONSTRAINT FK_CERT_RESUME_COPY_RESUME FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);


-- RESUME_COPY
DROP SEQUENCE SEQ_RESUME_COPY_ID;
CREATE SEQUENCE SEQ_RESUME_COPY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- RESUME_TAG_COPY
DROP SEQUENCE SEQ_RESUME_TAG_COPY_ID;
CREATE SEQUENCE SEQ_RESUME_TAG_COPY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CAREER_COPY
DROP SEQUENCE SEQ_CAREER_COPY_ID;
CREATE SEQUENCE SEQ_CAREER_COPY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- EDUCATION_COPY
DROP SEQUENCE SEQ_EDUCATION_COPY_ID;
CREATE SEQUENCE SEQ_EDUCATION_COPY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- SCHOOL_COPY
DROP SEQUENCE SEQ_SCHOOL_COPY_ID;
CREATE SEQUENCE SEQ_SCHOOL_COPY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- PORTFOLIO_COPY
DROP SEQUENCE SEQ_PORTFOLIO_COPY_ID;
CREATE SEQUENCE SEQ_PORTFOLIO_COPY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CERTIFICATE_RESUME_COPY
DROP SEQUENCE SEQ_CERTIFICATE_RESUME_COPY_ID;
CREATE SEQUENCE SEQ_CERTIFICATE_RESUME_COPY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

