DROP SEQUENCE chat_message_seq;
CREATE SEQUENCE chat_message_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


DROP SEQUENCE JOB_GROUP_ID_SEQ;
CREATE SEQUENCE JOB_GROUP_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE JOB_ID_SEQ;
CREATE SEQUENCE JOB_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE CERTIFICATE_ID_SEQ;
CREATE SEQUENCE CERTIFICATE_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SEQ_JOB_WELFARE_ID;

CREATE SEQUENCE SEQ_JOB_WELFARE_ID
    START WITH 1
    INCREMENT BY 1;

drop SEQUENCE SEQ_JOB_POST_FILE_ID;
CREATE SEQUENCE SEQ_JOB_POST_FILE_ID
    START WITH 1
    INCREMENT BY 1;

DROP SEQUENCE TAG_ID_SEQ;
CREATE SEQUENCE TAG_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE STATE_ID_SEQ;
CREATE SEQUENCE STATE_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE POSTAL_CODE_ID_SEQ;
CREATE SEQUENCE POSTAL_CODE_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE MEMBER_ID_SEQ;
CREATE SEQUENCE MEMBER_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE COMPANY_ID_SEQ;
CREATE SEQUENCE COMPANY_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE CERTIFICATE_RESUME_ID_SEQ;
CREATE SEQUENCE CERTIFICATE_RESUME_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE CAREER_ID_SEQ;
CREATE SEQUENCE CAREER_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE EDU_ID_SEQ;
CREATE SEQUENCE EDU_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SCHOOL_ID_SEQ;
CREATE SEQUENCE SCHOOL_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE PORTFOLIO_ID_SEQ;
CREATE SEQUENCE PORTFOLIO_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE RESUME_ID_SEQ;
CREATE SEQUENCE RESUME_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE UPLOAD_ID_SEQ;
CREATE SEQUENCE UPLOAD_ID_SEQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE RM_ID_SEQ;
-- CREATE SEQUENCE RM_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE RESUME_TAG_ID_SEQ;
CREATE SEQUENCE RESUME_TAG_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE JOB_POST_ID_SEQ;
CREATE SEQUENCE JOB_POST_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE JOB_POST_QUESTION_ID_SEQ;

CREATE SEQUENCE JOB_POST_QUESTION_ID_SEQ
    START WITH 1
    INCREMENT BY 1;
DROP SEQUENCE JOB_POST_ANSWER_ID_SEQ;

CREATE SEQUENCE JOB_POST_ANSWER_ID_SEQ
    START WITH 1
    INCREMENT BY 1;
DROP SEQUENCE COMMUNITY_ID_SEQ;
CREATE SEQUENCE COMMUNITY_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE COMMUNITY_FILE_ID_SEQ;
CREATE SEQUENCE COMMUNITY_FILE_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE POST_COMMENT_ID_SEQ;
CREATE SEQUENCE POST_COMMENT_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE REPLY_ID_SEQ;
CREATE SEQUENCE REPLY_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE CR_ID_SEQ;
CREATE SEQUENCE CR_ID_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE CM_ID_SEQ;
CREATE SEQUENCE CM_ID_SEQ START WITH 1 INCREMENT BY 1;

--공지시퀀스넘버
DROP SEQUENCE NOTICE_ID_SEQ;
CREATE SEQUENCE NOTICE_ID_SEQ START WITH 1 INCREMENT BY 1;

--공지 머리말
DROP SEQUENCE NOTICE_CATEGORY_ID_SEQ;
CREATE SEQUENCE NOTICE_CATEGORY_ID_SEQ START WITH 1 INCREMENT BY 1;
