--첫 번째 이력서(아무것도 없음)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, 'AI 반도체 연구원 김가람의 이력서 기본 인적사항', '김가람', '20000101', '010-1234-5687', 'user1@example.com', 14750, '305호', 'AI와 반도체 기술이 융합되는 시대에, 차세대 연산 구조를 선도하는 연구원이 되기 위해 지원하게 되었습니다.
학부 시절부터 전자공학과 인공지능을 복수전공하며, 딥러닝 모델의 하드웨어 구현 효율성에 깊은 관심을 가졌습니다.
졸업 논문에서는 CNN 모델을 FPGA에 최적화하여 성능과 전력 소비를 개선한 프로젝트를 수행하였고,
이를 통해 AI 알고리즘이 실질적인 반도체 구조로 구현되는 과정에 대한 통찰을 얻었습니다.
삼성전자 주관 AI반도체 해커톤에 참가해 Top3에 입상하며 실무 감각을 키운 경험도 있습니다.
특히, 병렬 연산 최적화 및 메모리 인터페이스 설계에 큰 흥미를 느껴 지속적인 학습을 이어가고 있습니다.
빠르게 발전하는 AI 반도체 분야에서 실질적인 기술 혁신을 이끌어내는 연구원이 되고 싶습니다.
깊이 있는 분석력과 꾸준한 학습 태도를 바탕으로, 귀 연구소의 목표에 부합하는 인재가 되겠습니다.
항상 문제의 본질을 파악하고, 창의적인 해결책을 제시하는 연구자가 되기 위해 노력하겠습니다.
감사합니다.', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');


--두 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, 'AI 반도체 연구원 김가람의 이력서 학력', '김가람', '20000101', '010-1234-5687', 'user1@example.com', 14750, '305호', 'AI와 반도체 기술이 융합되는 시대에, 차세대 연산 구조를 선도하는 연구원이 되기 위해 지원하게 되었습니다. 학부 시절부터 전자공학과 인공지능을 복수전공하며, 딥러닝 모델의 하드웨어 구현 효율성에 깊은 관심을 가졌습니다. 졸업 논문에서는 CNN 모델을 FPGA에 최적화하여 성능과 전력 소비를 개선한 프로젝트를 수행하였고, 이를 통해 AI 알고리즘이 실질적인 반도체 구조로 구현되는 과정에 대한 통찰을 얻었습니다. 삼성전자 주관 AI반도체 해커톤에 참가해 Top3에 입상하며 실무 감각을 키운 경험도 있습니다. 특히, 병렬 연산 최적화 및 메모리 인터페이스 설계에 큰 흥미를 느껴 지속적인 학습을 이어가고 있습니다. 빠르게 발전하는 AI 반도체 분야에서 실질적인 기술 혁신을 이끌어내는 연구원이 되고 싶습니다. 깊이 있는 분석력과 꾸준한 학습 태도를 바탕으로, 귀 연구소의 목표에 부합하는 인재가 되겠습니다. 항상 문제의 본질을 파악하고, 창의적인 해결책을 제시하는 연구자가 되기 위해 노력하겠습니다. ', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '마포고등학교',
    TO_DATE('2017-02', 'YYYY-MM'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'univ4', '성균관대학교',  '소프트웨어학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'master', '연세대학교 대학원',  '컴퓨터과학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);


--세 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, 'AI 반도체 연구원 김가람의 이력서 학력 스킬', '김가람', '20000101', '010-1234-5687', 'user1@example.com', 14750, '305호', 'AI와 반도체 기술이 융합되는 시대에, 차세대 연산 구조를 선도하는 연구원이 되기 위해 지원하게 되었습니다. 학부 시절부터 전자공학과 인공지능을 복수전공하며, 딥러닝 모델의 하드웨어 구현 효율성에 깊은 관심을 가졌습니다. 졸업 논문에서는 CNN 모델을 FPGA에 최적화하여 성능과 전력 소비를 개선한 프로젝트를 수행하였고, 이를 통해 AI 알고리즘이 실질적인 반도체 구조로 구현되는 과정에 대한 통찰을 얻었습니다. 삼성전자 주관 AI반도체 해커톤에 참가해 Top3에 입상하며 실무 감각을 키운 경험도 있습니다. 특히, 병렬 연산 최적화 및 메모리 인터페이스 설계에 큰 흥미를 느껴 지속적인 학습을 이어가고 있습니다. 빠르게 발전하는 AI 반도체 분야에서 실질적인 기술 혁신을 이끌어내는 연구원이 되고 싶습니다. 깊이 있는 분석력과 꾸준한 학습 태도를 바탕으로, 귀 연구소의 목표에 부합하는 인재가 되겠습니다. 항상 문제의 본질을 파악하고, 창의적인 해결책을 제시하는 연구자가 되기 위해 노력하겠습니다. ', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '마포고등학교',
    TO_DATE('2017-02', 'YYYY-MM'), '졸업'
);

INSERT INTO SCHOOL (
SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'univ4', '성균관대학교',  '소프트웨어학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'master', '연세대학교 대학원',  '컴퓨터과학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 178, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 182, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 700, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 702, SYSDATE, SYSDATE);


--네 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, 'AI 반도체 연구원 김가람의 이력서 학력 스킬 경력', '김가람', '20000101', '010-1234-5687', 'user1@example.com', 14750, '305호', 'AI와 반도체 기술이 융합되는 시대에, 차세대 연산 구조를 선도하는 연구원이 되기 위해 지원하게 되었습니다. 학부 시절부터 전자공학과 인공지능을 복수전공하며, 딥러닝 모델의 하드웨어 구현 효율성에 깊은 관심을 가졌습니다. 졸업 논문에서는 CNN 모델을 FPGA에 최적화하여 성능과 전력 소비를 개선한 프로젝트를 수행하였고, 이를 통해 AI 알고리즘이 실질적인 반도체 구조로 구현되는 과정에 대한 통찰을 얻었습니다. 삼성전자 주관 AI반도체 해커톤에 참가해 Top3에 입상하며 실무 감각을 키운 경험도 있습니다. 특히, 병렬 연산 최적화 및 메모리 인터페이스 설계에 큰 흥미를 느껴 지속적인 학습을 이어가고 있습니다. 빠르게 발전하는 AI 반도체 분야에서 실질적인 기술 혁신을 이끌어내는 연구원이 되고 싶습니다. 깊이 있는 분석력과 꾸준한 학습 태도를 바탕으로, 귀 연구소의 목표에 부합하는 인재가 되겠습니다. 항상 문제의 본질을 파악하고, 창의적인 해결책을 제시하는 연구자가 되기 위해 노력하겠습니다. ', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '마포고등학교',
    TO_DATE('2017-02', 'YYYY-MM'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'univ4', '성균관대학교',  '소프트웨어학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'master', '연세대학교 대학원',  '컴퓨터과학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 178, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 182, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 700, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 702, SYSDATE, SYSDATE);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '네이버', '클라우드플랫폼개발실', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2022-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);


--다섯 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, 'AI 반도체 연구원 김가람의 이력서 최종본', '김가람', '20000101', '010-1234-5687', 'user1@example.com', 14750, '305호', 'AI와 반도체 기술이 융합되는 시대에, 차세대 연산 구조를 선도하는 연구원이 되기 위해 지원하게 되었습니다. 학부 시절부터 전자공학과 인공지능을 복수전공하며, 딥러닝 모델의 하드웨어 구현 효율성에 깊은 관심을 가졌습니다. 졸업 논문에서는 CNN 모델을 FPGA에 최적화하여 성능과 전력 소비를 개선한 프로젝트를 수행하였고, 이를 통해 AI 알고리즘이 실질적인 반도체 구조로 구현되는 과정에 대한 통찰을 얻었습니다. 삼성전자 주관 AI반도체 해커톤에 참가해 Top3에 입상하며 실무 감각을 키운 경험도 있습니다. 특히, 병렬 연산 최적화 및 메모리 인터페이스 설계에 큰 흥미를 느껴 지속적인 학습을 이어가고 있습니다. 빠르게 발전하는 AI 반도체 분야에서 실질적인 기술 혁신을 이끌어내는 연구원이 되고 싶습니다. 깊이 있는 분석력과 꾸준한 학습 태도를 바탕으로, 귀 연구소의 목표에 부합하는 인재가 되겠습니다. 항상 문제의 본질을 파악하고, 창의적인 해결책을 제시하는 연구자가 되기 위해 노력하겠습니다. ', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '마포고등학교',
    TO_DATE('2017-02', 'YYYY-MM'), '졸업'
);

INSERT INTO SCHOOL (
SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'univ4', '성균관대학교',  '소프트웨어학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'master', '연세대학교 대학원',  '컴퓨터과학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 178, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 182, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 700, SYSDATE, SYSDATE);

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 702, SYSDATE, SYSDATE);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '네이버', '클라우드플랫폼개발실', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2022-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '카카오', '클라우드플랫폼개발실', TO_DATE('2022-06-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);

--첫 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '백엔드/서버 개발자, 대졸, 관련 직무 경력 6년', '김서연', '19980101', '010-0000-0001', 'user1@example.com', 14750, '305호', '열정적인 백엔드/서버 개발자입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '대전예술고등학교',
    TO_DATE('2011-02', 'YYYY-MM'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'univ4', '홍익대학교', '컴퓨터공학과',
    TO_DATE('2011-03-01', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '정보처리산업기사', '한국산업인력공단', TO_DATE('2018-09-20', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '산업안전기사', '한국산업인력공단', TO_DATE('2022-04-05', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '건설안전기사', '한국산업인력공단', TO_DATE('2023-12-22', 'YYYY-MM-DD'));

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '멀티캠퍼스', '데이터베이스 실습', TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'),
    'SQL, NoSQL, 데이터 모델링 실습'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '카카오', '웹서비스개발팀', TO_DATE('2015-06-01', 'YYYY-MM-DD'), TO_DATE('2017-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'SK', '웹서비스개발팀', TO_DATE('2017-06-11', 'YYYY-MM-DD'), TO_DATE('2023-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);

--두 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '웹개발자, 학력 없음, 경력 없음', '이준호', '19920102', '010-0000-0002', 'random2@testmail.com', 14751, '306호', '성실한 웹개발자입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 220, SYSDATE, SYSDATE); -- Mysql

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 210, SYSDATE, SYSDATE); -- Spring Boot

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '정보처리산업기사', '한국산업인력공단', TO_DATE('2020-03-10', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '전자계산기기사', '한국산업인력공단', TO_DATE('2022-08-25', 'YYYY-MM-DD'));

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '코드스테이츠', '웹 개발자 부트캠프', TO_DATE('2021-07-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    'JavaScript, React, Node.js 등 실무 중심 교육'
);


--세 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '웹 디자이너, 초대졸, 관련 직군 경력 1년, 그 외 경력 1년', '박지우', '19960103', '010-0000-0003', 'data3@demo.net', 14752, '307호', '꼼꼼한 웹 디자이너입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 266, SYSDATE, SYSDATE); -- Illustrator

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '부산국제고등학교',
    TO_DATE('2015-02', 'YYYY-MM'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'univ2', '유한대학교', '시각디자인과',
    TO_DATE('2015-03-01', 'YYYY-MM-DD'), TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '제품디자인기사', '한국산업인력공단', TO_DATE('2023-02-20', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '실내건축기사', '한국산업인력공단', TO_DATE('2024-10-05', 'YYYY-MM-DD'));

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '카카오', '웹서비스개발팀', TO_DATE('2015-06-01', 'YYYY-MM-DD'), TO_DATE('2017-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '네이버', '모바일마케팅팀', TO_DATE('2022-10-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), '모바일 마케터', 25, 2, 4500, '모바일 광고 캠페인 기획, 퍼포먼스 마케팅'
);

--네 번째 이력서
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '광고기획자, 고졸, 관련 직무 3년, 그 외 경력 1년', '최민재', '19930104', '010-0000-0004', 'fake4@sample.org', 14753, '308호', '책임감 강한 광고기획자입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 1, SYSDATE, SYSDATE); -- 신사업계획

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '천안고등학교',
    TO_DATE('2018-02', 'YYYY-MM'), '졸업'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '제일기획', '광고기획팀', TO_DATE('2020-04-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '광고기획자', 3, 1, 4200, '광고 캠페인 기획, 크리에이티브 전략 수립'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '롯데그룹', '마케팅기획팀', TO_DATE('2019-12-05', 'YYYY-MM-DD'), TO_DATE('2022-12-31', 'YYYY-MM-DD'), '마케팅 기획자', 7, 1, 4000, '마케팅 전략 수립, 캠페인 기획, 데이터 분석'
);

--다섯 번째 이력서	
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '글로벌 마케터, 석사, 관련 직무 2년', '정하늘', '20000105', '010-0000-0005', 'dummy5@email.com', 14754, '309호', '창의적인 글로벌 마케터입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 22, SYSDATE, SYSDATE); -- 기획서 작성

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 14, SYSDATE, SYSDATE); -- 시장조사

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 55, SYSDATE, SYSDATE); -- SNS 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 58, SYSDATE, SYSDATE); -- 구글 광고

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 60, SYSDATE, SYSDATE); -- 바이럴 마케팅

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'high', '광주국제고등학교',
    TO_DATE('2018-02', 'YYYY-MM'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'univ4', '중앙대학교', '광고홍보학과',
    TO_DATE('2018-03-01', 'YYYY-MM-DD'), TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, 'master', '고려대학교 대학원', '광고홍보학과',
    TO_DATE('2017-03-02', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);


INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '텔레마케팅관리사', '한국산업인력공단', TO_DATE('2020-02-28', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '영사산업기사', '한국산업인력공단', TO_DATE('2023-11-10', 'YYYY-MM-DD'));

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '마케팅스쿨', '브랜드 커뮤니케이션 워크숍', TO_DATE('2023-01-05', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '브랜드 메시지, 콘텐츠 기획, 커뮤니케이션 전략 실습'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, RESUME_ID_SEQ.CURRVAL, '삼성전자', '글로벌마케팅팀', TO_DATE('2023-08-01', 'YYYY-MM-DD'), TO_DATE('2025-08-10', 'YYYY-MM-DD'), '글로벌 마케터', 19, 2, 5000, '글로벌 시장 분석, 브랜드 전략 수립, 해외 마케팅 실행'
);





commit;