--이력서 더미데이터
-- 1번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '김서연의 이력서 1', '김서연', '19980101', '010-0000-0001', 'user1@example.com', 14750, '305호', '열정적인 백엔드/서버 개발자입니다.', 21, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 2번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '이준호의 이력서 1', '이준호', '19920102', '010-0000-0002', 'random2@testmail.com', 14751, '306호', '성실한 웹개발자입니다.', 22, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 3번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '박지우의 이력서 1', '박지우', '19960103', '010-0000-0003', 'data3@demo.net', 14752, '307호', '꼼꼼한 가구 디자이너입니다.', 23, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 4번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '최민재의 이력서 1', '최민재', '19930104', '010-0000-0004', 'fake4@sample.org', 14753, '308호', '책임감 강한 광고기획자입니다.', 4, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 5번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '정하늘의 이력서 1', '정하늘', '20000105', '010-0000-0005', 'dummy5@email.com', 14754, '309호', '창의적인 글로벌 마케터입니다.', 5, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 6번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '윤지훈의 이력서 1', '윤지훈', '19960106', '010-0000-0006', 'info6@mockdata.net', 14755, '310호', '도전적인 마케팅 기획자입니다.', 6, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 7번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '한예린의 이력서 1', '한예린', '19990107', '010-0000-0007', 'random7@trymail.com', 14756, '311호', '논리적인 웹 개발자입니다.', 7, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 8번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRthDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '오지호의 이력서 1', '오지호', '19970108', '010-0000-0008', 'demo8@testexample.org', 14757, '312호', '적극적인 모바일 디자이너입니다.', 8, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 9번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '장민서의 이력서 1', '장민서', '19990109', '010-0000-0009', 'sample9@mailbox.net', 14758, '313호', '열정적인 모바일 마케터입니다.', 9, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 10번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '백하람의 이력서 1', '백하람', '20000110', '010-0000-0010', 'trial10@dummydata.com', 14759, '314호', '책임감 강한 브랜드 기획자입니다.', 10, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 11번 (member1)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '김서연의 이력서 2', '김서연', '19980101', '010-0000-0001', 'user1@example.com', 14750, '305호', '열정적인 백엔드/서버 개발자입니다.', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 12번 (member1)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '김서연의 이력서 3', '김서연', '19980101', '010-0000-0001', 'user1@example.com', 14750, '305호', '열정적인 백엔드/서버 개발자입니다.', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 13번 (member2)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '이준호의 이력서 2', '이준호', '19920102', '010-0000-0002', 'random2@testmail.com', 14751, '306호', '성실한 웹개발자입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 14번 (member2)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '이준호의 이력서 3', '이준호', '19920102', '010-0000-0002', 'random2@testmail.com', 14751, '306호', '성실한 웹개발자입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 15번 (member3)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '박지우의 이력서 2', '박지우', '19960103', '010-0000-0003', 'data3@demo.net', 14752, '307호', '꼼꼼한 가구 디자이너입니다.', 3, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 16번 (member3)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '박지우의 이력서 3', '박지우', '19960103', '010-0000-0003', 'data3@demo.net', 14752, '307호', '꼼꼼한 가구 디자이너입니다.', 3, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 17번 (member4)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '최민재의 이력서 2', '최민재', '19930104', '010-0000-0004', 'fake4@sample.org', 14753, '308호', '책임감 강한 광고기획자입니다.', 4, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 18번 (member5)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '정하늘의 이력서 2', '정하늘', '20000105', '010-0000-0005', 'dummy5@email.com', 14754, '309호', '창의적인 글로벌 마케터입니다.', 5, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 19번 (member6)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '윤지훈의 이력서 2', '윤지훈', '19960106', '010-0000-0006', 'info6@mockdata.net', 14755, '310호', '도전적인 마케팅 기획자입니다.', 6, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 20번 (member7)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '한예린의 이력서 2', '한예린', '19990107', '010-0000-0007', 'random7@trymail.com', 14756, '311호', '논리적인 웹 개발자입니다.', 7, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 21번 (member8)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRthDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '오지호의 이력서 2', '오지호', '19970108', '010-0000-0008', 'demo8@testexample.org', 14757, '312호', '적극적인 모바일 디자이너입니다.', 8, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 22번 (member9)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '장민서의 이력서 2', '장민서', '19990109', '010-0000-0009', 'sample9@mailbox.net', 14758, '313호', '열정적인 모바일 마케터입니다.', 9, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 23번 (member10)
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '백하람의 이력서 2', '백하람', '20000110', '010-0000-0010', 'trial10@dummydata.com', 14759, '314호', '책임감 강한 브랜드 기획자입니다.', 10, 'profile.jpg', SYSDATE, SYSDATE, '1');


-- 이력서 태그(스킬)
-- RESUME_ID: 1 (member1)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 1, 209, SYSDATE, SYSDATE); -- Java

-- RESUME_ID: 3 (member3)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 3, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 3, 266, SYSDATE, SYSDATE); -- Illustrator

-- RESUME_ID: 4 (member4)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 4, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 4, 6, SYSDATE, SYSDATE); -- 데이터분석

-- RESUME_ID: 5 (member5)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 5, 22, SYSDATE, SYSDATE); -- 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 5, 14, SYSDATE, SYSDATE); -- 시장조사

-- RESUME_ID: 6 (member6)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 6, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 6, 6, SYSDATE, SYSDATE); -- 데이터분석

-- RESUME_ID: 7 (member7)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 7, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 7, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 7, 214, SYSDATE, SYSDATE); -- React

-- RESUME_ID: 8 (member8)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 8, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 8, 266, SYSDATE, SYSDATE); -- Illustrator

-- RESUME_ID: 9  (member9)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 22, SYSDATE, SYSDATE); -- 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 14, SYSDATE, SYSDATE); -- 시장조사

-- RESUME_ID: 10  (member10)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 10, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 10, 6, SYSDATE, SYSDATE); -- 데이터분석

-- RESUME_ID: 11 (member1)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 11, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 11, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 11, 220, SYSDATE, SYSDATE); -- Mysql

-- RESUME_ID: 12 (member1)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 12, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 12, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 12, 220, SYSDATE, SYSDATE); -- Mysql

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 12, 210, SYSDATE, SYSDATE); -- Spring Boot

-- RESUME_ID: 13 (member2)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 13, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 13, 213, SYSDATE, SYSDATE); -- JavaScript

-- RESUME_ID: 14 (member2)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 14, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 14, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 14, 210, SYSDATE, SYSDATE); -- Spring Boot

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 14, 206, SYSDATE, SYSDATE); -- Ajax

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 14, 217, SYSDATE, SYSDATE); -- Python

-- RESUME_ID: 15 (member3)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 15, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 15, 266, SYSDATE, SYSDATE); -- Illustrator

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 15, 272, SYSDATE, SYSDATE); -- UI 디자인

-- RESUME_ID: 16 (member3)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 16, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 16, 266, SYSDATE, SYSDATE); -- Illustrator

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 16, 272, SYSDATE, SYSDATE); -- UI 디자인

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 16, 254, SYSDATE, SYSDATE); -- 일러스트

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 16, 271, SYSDATE, SYSDATE); -- 시안디자인

-- RESUME_ID: 17 (member4)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 17, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 17, 6, SYSDATE, SYSDATE); -- 데이터분석

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 17, 15, SYSDATE, SYSDATE); -- 신사업기획

-- RESUME_ID: 18 (member5)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 18, 22, SYSDATE, SYSDATE); -- 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 18, 14, SYSDATE, SYSDATE); -- 시장조사

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 18, 55, SYSDATE, SYSDATE); -- SNS 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 18, 36, SYSDATE, SYSDATE); -- 검색광고

-- RESUME_ID: 19 (member6)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 19, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 19, 6, SYSDATE, SYSDATE); -- 데이터분석

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 19, 15, SYSDATE, SYSDATE); -- 신사업기획

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 19, 16, SYSDATE, SYSDATE); -- Excel

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 19, 3, SYSDATE, SYSDATE); -- 경영컨설팅

-- RESUME_ID: 20 (member7)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 20, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 20, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 20, 214, SYSDATE, SYSDATE); -- React

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 20, 212, SYSDATE, SYSDATE); -- MyBatis

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 20, 210, SYSDATE, SYSDATE); -- Spring Boot

-- RESUME_ID: 21 (member8)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 21, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 21, 266, SYSDATE, SYSDATE); -- Illustrator

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 21, 272, SYSDATE, SYSDATE); -- UI 디자인

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 21, 275, SYSDATE, SYSDATE); -- 웹디자인

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 21, 277, SYSDATE, SYSDATE); -- HTML/CSS 이해

-- RESUME_ID: 22 (member9)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 22, SYSDATE, SYSDATE); -- 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 14, SYSDATE, SYSDATE); -- 시장조사

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 55, SYSDATE, SYSDATE); -- SNS 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 58, SYSDATE, SYSDATE); -- 구글 광고

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 60, SYSDATE, SYSDATE); -- 바이럴 마케팅

-- RESUME_ID: 23 (member10)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 23, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 23, 6, SYSDATE, SYSDATE); -- 데이터분석

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 23, 15, SYSDATE, SYSDATE); -- 신사업기획

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 23, 5, SYSDATE, SYSDATE); -- 금융컨설팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 23, 11, SYSDATE, SYSDATE); -- 사업관리


--학력
-- RESUME_ID: 1 (member1)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 1, '고등학교', '서울과학고등학교',
    TO_DATE('2014-03-02', 'YYYY-MM-DD'), TO_DATE('2017-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 1, '대학교(4년)', '카이스트', '전산학과',
    TO_DATE('2017-03-01', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 2 (member2)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 2, '고등학교', '대전예술고등학교',
    TO_DATE('2008-03-02', 'YYYY-MM-DD'), TO_DATE('2011-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 2, '대학교(4년)', '홍익대학교', '컴퓨터공학과',
    TO_DATE('2011-03-01', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 3 (member3)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 3, '고등학교', '부산국제고등학교',
    TO_DATE('2012-03-02', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 3, '대학교(4년)', '연세대학교', '시각디자인과',
    TO_DATE('2015-03-01', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 4 (member4)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 4, '고등학교', '경기외국어고등학교',
    TO_DATE('2009-03-02', 'YYYY-MM-DD'), TO_DATE('2012-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 4, '대학교(4년)', '고려대학교', '경영학과',
    TO_DATE('2012-03-01', 'YYYY-MM-DD'), TO_DATE('2016-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 5 (member5)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 5, '고등학교', '한성과학고등학교',
    TO_DATE('2011-03-02', 'YYYY-MM-DD'), TO_DATE('2014-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 5, '대학교(4년)', '포항공과대학교', '신소재공학과',
    TO_DATE('2014-03-01', 'YYYY-MM-DD'), TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 6 (member6)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 6, '고등학교', '서울외국어고등학교',
    TO_DATE('2012-03-02', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 6, '대학교(4년)', '서강대학교', '커뮤니케이션학과',
    TO_DATE('2015-03-01', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 7 (member7)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 7, '고등학교', '대구소프트웨어고등학교',
    TO_DATE('2015-03-02', 'YYYY-MM-DD'), TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 7, '대학교(4년)', '한양대학교', '소프트웨어학부',
    TO_DATE('2018-03-01', 'YYYY-MM-DD'), TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 8 (member8)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 8, '고등학교', '부산과학고등학교',
    TO_DATE('2013-03-02', 'YYYY-MM-DD'), TO_DATE('2016-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 8, '대학교(4년)', '성균관대학교', '산업공학과',
    TO_DATE('2016-03-01', 'YYYY-MM-DD'), TO_DATE('2020-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 9 (member9)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 9, '고등학교', '광주국제고등학교',
    TO_DATE('2015-03-02', 'YYYY-MM-DD'), TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 9, '대학교(4년)', '중앙대학교', '광고홍보학과',
    TO_DATE('2018-03-01', 'YYYY-MM-DD'), TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 10 (member10)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 10, '고등학교', '인천외국어고등학교',
    TO_DATE('2012-03-02', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 11 (member1)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 11, '고등학교', '서울과학고등학교',
    TO_DATE('2014-03-02', 'YYYY-MM-DD'), TO_DATE('2017-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 11, '대학교(4년)', '카이스트', '전산학과',
    TO_DATE('2017-03-01', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 12 (member1)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 12, '고등학교', '서울과학고등학교',
    TO_DATE('2014-03-02', 'YYYY-MM-DD'), TO_DATE('2017-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 12, '대학교(4년)', '카이스트', '전산학과',
    TO_DATE('2017-03-01', 'YYYY-MM-DD'), TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 13 (member2)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 13, '고등학교', '대전예술고등학교',
    TO_DATE('2008-03-02', 'YYYY-MM-DD'), TO_DATE('2011-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 13, '대학교(4년)', '홍익대학교', '컴퓨터공학과',
    TO_DATE('2011-03-01', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 14 (member2)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 14, '고등학교', '대전예술고등학교',
    TO_DATE('2008-03-02', 'YYYY-MM-DD'), TO_DATE('2011-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 14, '대학교(4년)', '홍익대학교', '컴퓨터공학과',
    TO_DATE('2011-03-01', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 15 (member3)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 15, '고등학교', '부산국제고등학교',
    TO_DATE('2012-03-02', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 15, '대학교(4년)', '연세대학교', '시각디자인과',
    TO_DATE('2015-03-01', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 16 (member3)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 16, '고등학교', '부산국제고등학교',
    TO_DATE('2012-03-02', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 16, '대학교(4년)', '연세대학교', '시각디자인과',
    TO_DATE('2015-03-01', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 17 (member4)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 17, '고등학교', '경기외국어고등학교',
    TO_DATE('2009-03-02', 'YYYY-MM-DD'), TO_DATE('2012-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 17, '대학교(4년)', '고려대학교', '경영학과',
    TO_DATE('2012-03-01', 'YYYY-MM-DD'), TO_DATE('2016-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 18 (member5)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 18, '고등학교', '한성과학고등학교',
    TO_DATE('2016-03-02', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 18, '대학교(4년)', '포항공과대학교', '신소재공학과',
    TO_DATE('2019-03-01', 'YYYY-MM-DD'), TO_DATE('2023-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 19 (member6)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 19, '고등학교', '서울외국어고등학교',
    TO_DATE('2012-03-02', 'YYYY-MM-DD'), TO_DATE('2015-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 19, '대학교(4년)', '서강대학교', '커뮤니케이션학과',
    TO_DATE('2015-03-01', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 20 (member7)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 20, '고등학교', '대구소프트웨어고등학교',
    TO_DATE('2015-03-02', 'YYYY-MM-DD'), TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 20, '대학교(4년)', '한양대학교', '소프트웨어학부',
    TO_DATE('2018-03-01', 'YYYY-MM-DD'), TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 21 (member8)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 21, '고등학교', '부산과학고등학교',
    TO_DATE('2013-03-02', 'YYYY-MM-DD'), TO_DATE('2016-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 21, '대학교(4년)', '성균관대학교', '산업공학과',
    TO_DATE('2016-03-01', 'YYYY-MM-DD'), TO_DATE('2020-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 22 (member9)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 22, '고등학교', '광주국제고등학교',
    TO_DATE('2015-03-02', 'YYYY-MM-DD'), TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 22, '대학교(4년)', '중앙대학교', '광고홍보학과',
    TO_DATE('2018-03-01', 'YYYY-MM-DD'), TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 23 (member10)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 23, '고등학교', '인천외국어고등학교',
    TO_DATE('2016-03-02', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), '졸업'
);
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 23, '대학교(4년)', '부산대학교', '국제학부',
    TO_DATE('2022-03-01', 'YYYY-MM-DD'), TO_DATE('2025-06-16', 'YYYY-MM-DD'), '재학중'
);


--경력
-- RESUME_ID: 1 (member1)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 1, '네이버', '클라우드플랫폼개발실', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2022-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);

-- RESUME_ID: 2 (member2)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 2, '카카오', '웹서비스개발팀', TO_DATE('2015-06-01', 'YYYY-MM-DD'), TO_DATE('2017-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);

-- RESUME_ID: 3 (member3)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 3, '한국가구디자인연구소', '디자인팀', TO_DATE('2019-07-01', 'YYYY-MM-DD'), TO_DATE('2021-07-30', 'YYYY-MM-DD'), '가구 디자이너', 88, 7, 3500, '가구 설계, 3D 모델링, 프로토타입 제작'
);

-- RESUME_ID: 5 (member5)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 5, '삼성전자', '글로벌마케팅팀', TO_DATE('2023-08-01', 'YYYY-MM-DD'), TO_DATE('2025-06-30', 'YYYY-MM-DD'), '글로벌 마케터', 19, 2, 5000, '글로벌 시장 분석, 브랜드 전략 수립, 해외 마케팅 실행'
);

-- RESUME_ID: 6 (member6)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 6, '롯데그룹', '마케팅기획팀', TO_DATE('2019-12-05', 'YYYY-MM-DD'), TO_DATE('2022-12-31', 'YYYY-MM-DD'), '마케팅 기획자', 7, 1, 4000, '마케팅 전략 수립, 캠페인 기획, 데이터 분석'
);

-- RESUME_ID: 7 (member7)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 7, '쿠팡', '웹개발팀', TO_DATE('2022-09-01', 'YYYY-MM-DD'), TO_DATE('2023-09-20', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4700, '웹 서비스 개발, 프론트엔드/백엔드 통합 개발'
);

-- RESUME_ID: 8 (member8)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 8, '카카오엔터프라이즈', '디자인팀', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '모바일 디자이너', 100, 7, 3800, '모바일 앱 UI/UX 디자인, 프로토타입 제작'
);

-- RESUME_ID: 9 (member9)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 9, '네이버', '모바일마케팅팀', TO_DATE('2022-10-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), '모바일 마케터', 25, 2, 4500, '모바일 광고 캠페인 기획, 퍼포먼스 마케팅'
);

-- RESUME_ID: 10 (member10)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 10, '현대백화점', '브랜드기획팀', TO_DATE('2019-06-01', 'YYYY-MM-DD'), TO_DATE('2021-07-31', 'YYYY-MM-DD'), '브랜드 기획자', 10, 1, 4300, '브랜드 전략 수립, 콘셉트 개발, 마케팅 플래닝'
);

-- RESUME_ID: 11 (member1)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 11, '네이버', '클라우드플랫폼개발실', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2022-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 11, '카카오톡', '클라우드플랫폼개발실', TO_DATE('2022-06-21', 'YYYY-MM-DD'), TO_DATE('2024-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);

-- RESUME_ID: 12 (member1)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 12, '네이버', '클라우드플랫폼개발실', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2022-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 12, '카카오톡', '클라우드플랫폼개발실', TO_DATE('2022-06-21', 'YYYY-MM-DD'), TO_DATE('2024-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 12, '쿠팡', '클라우드플랫폼개발실', TO_DATE('2024-07-21', 'YYYY-MM-DD'), TO_DATE('2025-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);

-- RESUME_ID: 13 (member2)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 13, '카카오', '웹서비스개발팀', TO_DATE('2015-06-01', 'YYYY-MM-DD'), TO_DATE('2017-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 13, 'SK', '웹서비스개발팀', TO_DATE('2017-06-11', 'YYYY-MM-DD'), TO_DATE('2019-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);

-- RESUME_ID: 14 (member2)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 14, '카카오', '웹서비스개발팀', TO_DATE('2015-06-01', 'YYYY-MM-DD'), TO_DATE('2017-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 14, 'SK', '웹서비스개발팀', TO_DATE('2017-06-11', 'YYYY-MM-DD'), TO_DATE('2019-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 14, '네이버', '웹서비스개발팀', TO_DATE('2019-06-11', 'YYYY-MM-DD'), TO_DATE('2023-07-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);

-- RESUME_ID: 15 (member3)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 15, '한국가구디자인연구소', '디자인팀', TO_DATE('2019-07-01', 'YYYY-MM-DD'), TO_DATE('2021-07-30', 'YYYY-MM-DD'), '가구 디자이너', 88, 7, 3500, '가구 설계, 3D 모델링, 프로토타입 제작'
);

-- RESUME_ID: 16 (member3)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 16, '한국가구디자인연구소', '디자인팀', TO_DATE('2019-07-01', 'YYYY-MM-DD'), TO_DATE('2021-07-30', 'YYYY-MM-DD'), '가구 디자이너', 88, 7, 3500, '가구 설계, 3D 모델링, 프로토타입 제작'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 16, 'iloom', '디자인팀', TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2024-08-30', 'YYYY-MM-DD'), '가구 디자이너', 88, 7, 3500, '가구 설계, 3D 모델링, 프로토타입 제작'
);

-- RESUME_ID: 17 (member4)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 17, '제일기획', '광고기획팀', TO_DATE('2020-04-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '광고기획자', 3, 1, 4200, '광고 캠페인 기획, 크리에이티브 전략 수립'
);

-- RESUME_ID: 18 (member5)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 18, '삼성전자', '글로벌마케팅팀', TO_DATE('2023-08-01', 'YYYY-MM-DD'), TO_DATE('2025-06-10', 'YYYY-MM-DD'), '글로벌 마케터', 19, 2, 5000, '글로벌 시장 분석, 브랜드 전략 수립, 해외 마케팅 실행'
);

-- RESUME_ID: 19 (member6)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 19, '롯데그룹', '마케팅기획팀', TO_DATE('2019-12-05', 'YYYY-MM-DD'), TO_DATE('2022-12-31', 'YYYY-MM-DD'), '마케팅 기획자', 7, 1, 4000, '마케팅 전략 수립, 캠페인 기획, 데이터 분석'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 19, '삼성SDS', '마케팅기획팀', TO_DATE('2023-01-15', 'YYYY-MM-DD'), TO_DATE('2025-05-31', 'YYYY-MM-DD'), '마케팅 기획자', 7, 1, 4000, '마케팅 전략 수립, 캠페인 기획, 데이터 분석'
);

-- RESUME_ID: 20 (member7)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 20, '쿠팡', '웹개발팀', TO_DATE('2022-09-01', 'YYYY-MM-DD'), TO_DATE('2023-09-20', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4700, '웹 서비스 개발, 프론트엔드/백엔드 통합 개발'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 20, '네이버', '웹개발팀', TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2025-05-20', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4700, '웹 서비스 개발, 프론트엔드/백엔드 통합 개발'
);

-- RESUME_ID: 21 (member8)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 21, '카카오엔터프라이즈', '디자인팀', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '모바일 디자이너', 100, 7, 3800, '모바일 앱 UI/UX 디자인, 프로토타입 제작'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 21, '구굴코리아', '디자인팀', TO_DATE('2023-06-25', 'YYYY-MM-DD'), TO_DATE('2025-05-31', 'YYYY-MM-DD'), '모바일 디자이너', 100, 7, 3800, '모바일 앱 UI/UX 디자인, 프로토타입 제작'
);

-- RESUME_ID: 22 (member9)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 22, '네이버', '모바일마케팅팀', TO_DATE('2022-10-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), '모바일 마케터', 25, 2, 4500, '모바일 광고 캠페인 기획, 퍼포먼스 마케팅'
);

-- RESUME_ID: 23 (member10)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 23, '현대백화점', '브랜드기획팀', TO_DATE('2019-06-01', 'YYYY-MM-DD'), TO_DATE('2021-07-31', 'YYYY-MM-DD'), '브랜드 기획자', 10, 1, 4300, '브랜드 전략 수립, 콘셉트 개발, 마케팅 플래닝'
);

INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 23, 'LG전자', '브랜드기획팀', TO_DATE('2022-06-01', 'YYYY-MM-DD'), TO_DATE('2025-06-16', 'YYYY-MM-DD'), '브랜드 기획자', 10, 1, 4300, '브랜드 전략 수립, 콘셉트 개발, 마케팅 플래닝'
);

--교육(비학력 이력)
-- RESUME_ID: 1 (member1)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 1, '멀티캠퍼스', '백엔드 개발자 양성과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    'Java, Spring, 데이터베이스 등 백엔드 개발 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 1, '패스트캠퍼스', '클라우드 인프라 실습', TO_DATE('2023-01-10', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    'AWS, Docker, Kubernetes 등 클라우드 환경 구축 실습'
);

-- RESUME_ID: 3 (member3)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 3, '한국디자인진흥원', '가구디자인 전문가 과정', TO_DATE('2018-06-01', 'YYYY-MM-DD'), TO_DATE('2018-11-30', 'YYYY-MM-DD'),
    '가구 설계, 목공, 디자인 소프트웨어 활용 교육'
);

-- RESUME_ID: 4 (member4)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 4, '광고기획 아카데미', '광고기획 전문가 과정', TO_DATE('2020-04-01', 'YYYY-MM-DD'), TO_DATE('2020-09-30', 'YYYY-MM-DD'),
    '광고기획, 크리에이티브 전략, 미디어 플래닝 실무 교육'
);

-- RESUME_ID: 5 (member5)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 5, '글로벌마케팅연구소', '글로벌 마케팅 전문가 과정', TO_DATE('2022-06-01', 'YYYY-MM-DD'), TO_DATE('2022-12-31', 'YYYY-MM-DD'),
    '글로벌 시장 분석, 브랜드 전략, SNS 마케팅 실무 교육'
);

-- RESUME_ID: 6 (member6)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 6, '마케팅기획 아카데미', '마케팅기획 전문가 과정', TO_DATE('2018-05-01', 'YYYY-MM-DD'), TO_DATE('2018-10-31', 'YYYY-MM-DD'),
    '마케팅 전략, 데이터 분석, 캠페인 기획 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 6, '마케팅스쿨', '브랜드 전략 워크숍', TO_DATE('2023-01-05', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '브랜드 포지셔닝, 콘셉트 개발 실습'
);

-- RESUME_ID: 8 (member8)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 8, '앱디자인 아카데미', '모바일 디자이너 과정', TO_DATE('2020-04-01', 'YYYY-MM-DD'), TO_DATE('2020-09-30', 'YYYY-MM-DD'),
    'Figma, Adobe XD, 모바일 앱 프로토타이핑 실무 교육'
);

-- RESUME_ID: 9 (member9)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 9, '모바일마케팅 아카데미', '모바일 마케팅 전문가 과정', TO_DATE('2021-06-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    '모바일 광고, 퍼포먼스 마케팅, 데이터 분석 실무 교육'
);

-- RESUME_ID: 11 (member1)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 11, '멀티캠퍼스', '백엔드 개발자 양성과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    'Java, Spring, 데이터베이스 등 백엔드 개발 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 11, '패스트캠퍼스', '클라우드 인프라 실습', TO_DATE('2023-01-10', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    'AWS, Docker, Kubernetes 등 클라우드 환경 구축 실습'
);

-- RESUME_ID: 12 (member1)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 12, '멀티캠퍼스', '백엔드 개발자 양성과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    'Java, Spring, 데이터베이스 등 백엔드 개발 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 12, '패스트캠퍼스', '클라우드 인프라 실습', TO_DATE('2023-01-10', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    'AWS, Docker, Kubernetes 등 클라우드 환경 구축 실습'
);

-- RESUME_ID: 13 (member2)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 13, '코드스테이츠', '웹 풀스택 부트캠프', TO_DATE('2017-04-01', 'YYYY-MM-DD'), TO_DATE('2017-09-30', 'YYYY-MM-DD'),
    '프론트엔드/백엔드 통합 개발 실무 교육'
);

-- RESUME_ID: 14 (member2)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 14, '코드스테이츠', '웹 풀스택 부트캠프', TO_DATE('2017-04-01', 'YYYY-MM-DD'), TO_DATE('2017-09-30', 'YYYY-MM-DD'),
    '프론트엔드/백엔드 통합 개발 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 14, '패스트캠퍼스', '프론트엔드 개발자 과정', TO_DATE('2019-07-01', 'YYYY-MM-DD'), TO_DATE('2019-12-31', 'YYYY-MM-DD'),
    'HTML, CSS, JavaScript, React 등 프론트엔드 개발 실무 교육'
);

-- RESUME_ID: 15 (member3)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 15, '한국디자인진흥원', '가구디자인 전문가 과정', TO_DATE('2018-06-01', 'YYYY-MM-DD'), TO_DATE('2018-11-30', 'YYYY-MM-DD'),
    '가구 설계, 목공, 디자인 소프트웨어 활용 교육'
);

-- RESUME_ID: 16 (member3)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 16, '한국디자인진흥원', '가구디자인 전문가 과정', TO_DATE('2018-06-01', 'YYYY-MM-DD'), TO_DATE('2018-11-30', 'YYYY-MM-DD'),
    '가구 설계, 목공, 디자인 소프트웨어 활용 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 16, '디자인스쿨', '3D 모델링 워크샵', TO_DATE('2023-03-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'),
    '3D 모델링, 렌더링, 시뮬레이션 실습'
);

-- RESUME_ID: 17 (member4)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 17, '광고기획 아카데미', '광고기획 전문가 과정', TO_DATE('2020-04-01', 'YYYY-MM-DD'), TO_DATE('2020-09-30', 'YYYY-MM-DD'),
    '광고기획, 크리에이티브 전략, 미디어 플래닝 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 17, '마케팅스쿨', '디지털 마케팅 워크숍', TO_DATE('2022-02-01', 'YYYY-MM-DD'), TO_DATE('2022-04-30', 'YYYY-MM-DD'),
    'SNS, 검색광고, 데이터 분석 실습'
);

-- RESUME_ID: 18 (member5)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 18, '글로벌마케팅연구소', '글로벌 마케팅 전문가 과정', TO_DATE('2022-06-01', 'YYYY-MM-DD'), TO_DATE('2022-12-31', 'YYYY-MM-DD'),
    '글로벌 시장 분석, 브랜드 전략, SNS 마케팅 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 18, '마케팅스쿨', '퍼포먼스 마케팅 워크숍', TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-09-30', 'YYYY-MM-DD'),
    '구글/페이스북 광고, 데이터 분석 실습'
);

-- RESUME_ID: 19 (member6)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 19, '마케팅기획 아카데미', '마케팅기획 전문가 과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    '마케팅 전략, 데이터 분석, 캠페인 기획 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 19, '마케팅스쿨', '브랜드 전략 워크숍', TO_DATE('2023-01-05', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '브랜드 포지셔닝, 콘셉트 개발 실습'
);

-- RESUME_ID: 20 (member7)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 20, '코드스테이츠', '웹 개발자 부트캠프', TO_DATE('2021-07-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    'JavaScript, React, Node.js 등 실무 중심 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 20, '멀티캠퍼스', '데이터베이스 실습', TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'),
    'SQL, NoSQL, 데이터 모델링 실습'
);

-- RESUME_ID: 21 (member8)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 21, '앱디자인 아카데미', '모바일 디자이너 과정', TO_DATE('2020-04-01', 'YYYY-MM-DD'), TO_DATE('2020-09-30', 'YYYY-MM-DD'),
    'Figma, Adobe XD, 모바일 앱 프로토타이핑 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 21, '디자인스쿨', 'UI/UX 워크숍', TO_DATE('2023-01-10', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '사용자 경험 설계, 인터랙션 디자인 실습'
);

-- RESUME_ID: 22 (member9)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 22, '모바일마케팅 아카데미', '모바일 마케팅 전문가 과정', TO_DATE('2021-06-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    '모바일 광고, 퍼포먼스 마케팅, 데이터 분석 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 22, '마케팅스쿨', '모바일 앱 마케팅 워크숍', TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'),
    '앱 광고, ASO, 유저 유입 전략 실습'
);

-- RESUME_ID: 23 (member10)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 23, '브랜드기획 아카데미', '브랜드기획 전문가 과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    '브랜드 전략, 콘셉트 개발, 마케팅 플래닝 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 23, '마케팅스쿨', '브랜드 커뮤니케이션 워크숍', TO_DATE('2023-01-05', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '브랜드 메시지, 콘텐츠 기획, 커뮤니케이션 전략 실습'
);


-- 자격증 더미데이터
SELECT * FROM CERTIFICATE;

-- RESUME_ID: 2 (member2)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 2, '정보처리기사', '한국산업인력공단', TO_DATE('2014-11-30', 'YYYY-MM-DD'));

-- RESUME_ID: 3 (member3)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 3, '시각디자인기사', '한국산업인력공단', TO_DATE('2018-02-18', 'YYYY-MM-DD'));

-- RESUME_ID: 4 (member4)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 4, '정보처리산업기사', '한국산업인력공단', TO_DATE('2020-10-12', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 4, '산업안전기사', '한국산업인력공단', TO_DATE('2021-01-25', 'YYYY-MM-DD'));

-- RESUME_ID: 5 (member5)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 5, '텔레마케팅관리사', '한국산업인력공단', TO_DATE('2023-02-28', 'YYYY-MM-DD'));

-- RESUME_ID: 6 (member6)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 6, '정보처리산업기사', '한국산업인력공단', TO_DATE('2018-09-20', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 6, '산업안전기사', '한국산업인력공단', TO_DATE('2022-04-05', 'YYYY-MM-DD'));

-- RESUME_ID: 7 (웹 개발자, JOB_GROUP_ID: 6)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 7, '정보처리산업기사', '한국산업인력공단', TO_DATE('2020-03-10', 'YYYY-MM-DD'));

-- RESUME_ID: 8 (모바일 디자이너, JOB_GROUP_ID: 7)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 8, '시각디자인기사', '한국산업인력공단', TO_DATE('2020-12-15', 'YYYY-MM-DD'));

-- RESUME_ID: 9 (모바일 마케터, JOB_GROUP_ID: 2)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 9, '영사산업기사', '한국산업인력공단', TO_DATE('2020-11-25', 'YYYY-MM-DD'));

-- RESUME_ID: 10 (브랜드 기획자, JOB_GROUP_ID: 1)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 10, '정보처리산업기사', '한국산업인력공단', TO_DATE('2022-10-30', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 10, '산업안전기사', '한국산업인력공단', TO_DATE('2023-03-05', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 10, '건설안전기사', '한국산업인력공단', TO_DATE('2022-12-10', 'YYYY-MM-DD'));

-- RESUME_ID: 11 (member1)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 11, '전자계산기기사', '한국산업인력공단', TO_DATE('2023-07-20', 'YYYY-MM-DD'));

-- RESUME_ID: 12 (member1)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 12, '전자계산기기사', '한국산업인력공단', TO_DATE('2023-07-20', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 12, '정보처리산업기사', '한국산업인력공단', TO_DATE('2024-10-15', 'YYYY-MM-DD')); 

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 12, '전자기사', '한국산업인력공단', TO_DATE('2025-03-10', 'YYYY-MM-DD'));

-- RESUME_ID: 13 (member2)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 13, '정보처리산업기사', '한국산업인력공단', TO_DATE('2014-11-30', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 13, '전자계산기기사', '한국산업인력공단', TO_DATE('2016-03-22', 'YYYY-MM-DD'));

-- RESUME_ID: 14 (member2)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 14, '정보처리산업기사', '한국산업인력공단', TO_DATE('2014-11-30', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 14, '전자계산기기사', '한국산업인력공단', TO_DATE('2016-03-22', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 14, '전자기사', '한국산업인력공단', TO_DATE('2018-09-15', 'YYYY-MM-DD'));

-- RESUME_ID: 15 (member3)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 15, '시각디자인기사', '한국산업인력공단', TO_DATE('2018-02-18', 'YYYY-MM-DD'));

-- RESUME_ID: 16 (member3)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 16, '시각디자인기사', '한국산업인력공단', TO_DATE('2018-02-18', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 16, '제품디자인기사', '한국산업인력공단', TO_DATE('2021-12-05', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 16, '실내건축기사', '한국산업인력공단', TO_DATE('2022-04-30', 'YYYY-MM-DD'));

-- RESUME_ID: 17 (member4)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 17, '정보처리산업기사', '한국산업인력공단', TO_DATE('2020-10-12', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 17, '산업안전기사', '한국산업인력공단', TO_DATE('2021-01-25', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 17, '건설안전기사', '한국산업인력공단', TO_DATE('2022-08-17', 'YYYY-MM-DD'));

-- RESUME_ID: 18 (member5)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 18, '텔레마케팅관리사', '한국산업인력공단', TO_DATE('2020-02-28', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 18, '영사산업기사', '한국산업인력공단', TO_DATE('2023-11-10', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 18, '시각디자인기사', '한국산업인력공단', TO_DATE('2024-03-15', 'YYYY-MM-DD'));

-- RESUME_ID: 19 (member6)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 19, '정보처리산업기사', '한국산업인력공단', TO_DATE('2018-09-20', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 19, '산업안전기사', '한국산업인력공단', TO_DATE('2022-04-05', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 19, '건설안전기사', '한국산업인력공단', TO_DATE('2023-12-22', 'YYYY-MM-DD'));

-- RESUME_ID: 20 (member7)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 20, '정보처리산업기사', '한국산업인력공단', TO_DATE('2020-03-10', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 20, '전자계산기기사', '한국산업인력공단', TO_DATE('2022-08-25', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 20, '전자기사', '한국산업인력공단', TO_DATE('2023-01-30', 'YYYY-MM-DD'));

-- RESUME_ID: 21 (member8)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 21, '시각디자인기사', '한국산업인력공단', TO_DATE('2020-12-15', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 21, '제품디자인기사', '한국산업인력공단', TO_DATE('2023-02-20', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 21, '실내건축기사', '한국산업인력공단', TO_DATE('2024-10-05', 'YYYY-MM-DD'));

-- RESUME_ID: 22 (member9)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 22, '영사산업기사', '한국산업인력공단', TO_DATE('2020-11-25', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 22, '텔레마케팅관리사', '한국산업인력공단', TO_DATE('2023-01-10', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 22, '시각디자인기사', '한국산업인력공단', TO_DATE('2023-04-18', 'YYYY-MM-DD'));

-- RESUME_ID: 23 (member10)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 23, '정보처리산업기사', '한국산업인력공단', TO_DATE('2019-10-30', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 23, '산업안전기사', '한국산업인력공단', TO_DATE('2020-03-05', 'YYYY-MM-DD'));

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ISSUING_AUTHORITY, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 23, '건설안전기사', '한국산업인력공단', TO_DATE('2020-12-10', 'YYYY-MM-DD'));


COMMIT;