-- MySQL Resume Copy 테이블 정의 파일
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS RESUME_COPY;
CREATE TABLE RESUME_COPY (
    RESUME_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESUME_TITLE VARCHAR(3000),
    NAME VARCHAR(3000),
    BIRTHDATE DATE,
    PHONENUMBER VARCHAR(3000),
    EMAIL VARCHAR(3000),
    POSTAL_CODE_ID INT,
    ADDRESS VARCHAR(3000),
    SELF_INTRODUCTION VARCHAR(3000),
    MEMBER_ID INT,
    PROFILE VARCHAR(3000),
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_PUBLIC TINYINT(1),
    MATCH_SCORE INT,
    CONSTRAINT FK_MEMBER_TO_RESUME_COPY FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

-- Resume_Tag_Copy
DROP TABLE IF EXISTS RESUME_TAG_COPY;
CREATE TABLE RESUME_TAG_COPY (
    RESUME_TAG_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESUME_ID INT,
    TAG_ID INT,
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_RES_TAG_COPY_RESUME FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RES_TAG_COPY_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID) ON DELETE CASCADE
);

-- Career_Copy
DROP TABLE IF EXISTS CAREER_COPY;
CREATE TABLE CAREER_COPY (
    CAREER_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESUME_ID INT,
    COMPANY_NAME VARCHAR(3000),
    DEPARTMENT_NAME VARCHAR(3000),
    HIRE_YM DATE,
    RESIGN_YM DATE,
    POSITION VARCHAR(3000),
    JOB_ID INT,
    JOB_GROUP_ID INT,
    SALARY INT,
    DETAIL VARCHAR(3000),
    CONSTRAINT FK_RESUME_COPY_TO_CAREER_COPY FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE,
    CONSTRAINT FK_JOB_TO_CAREER_COPY FOREIGN KEY (JOB_ID) REFERENCES JOB(JOB_ID),
    CONSTRAINT FK_JOB_GROUP_TO_CAREER_COPY FOREIGN KEY (JOB_GROUP_ID) REFERENCES JOB_GROUP(JOB_GROUP_ID)
);

-- Education_Copy
DROP TABLE IF EXISTS EDUCATION_COPY;
CREATE TABLE EDUCATION_COPY (
    EDU_ID INT AUTO_INCREMENT PRIMARY KEY,
    Resume_ID INT,
    EDU_INSTITUTION VARCHAR(3000),
    EDU_NAME VARCHAR(3000),
    START_DATE DATE,
    END_DATE DATE,
    CONTENT VARCHAR(3000),
    CONSTRAINT FK_EDU_COPY_RESUME FOREIGN KEY (Resume_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);

-- School_Copy
DROP TABLE IF EXISTS SCHOOL_COPY;
CREATE TABLE SCHOOL_COPY (
    SCHOOL_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESUME_ID INT,
    SORTATION VARCHAR(3000),
    SCHOOL_NAME VARCHAR(3000),
    YEAR_OF_GRADUATION VARCHAR(3000),
    START_DATE DATE,
    END_DATE DATE,
    MAJOR_NAME VARCHAR(3000),
    STATUS VARCHAR(3000),
    CONSTRAINT FK_RESUME_COPY_TO_SCHOOL_COPY FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);

-- Portfolio_Copy
DROP TABLE IF EXISTS PORTFOLIO_COPY;
CREATE TABLE PORTFOLIO_COPY (
    PORTFOLIO_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESUME_ID INT,
    FILE_NAME VARCHAR(3000),
    STORED_FILE_NAME VARCHAR(3000),
    FILE_EXTENSION VARCHAR(300),
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_PORT_COPY_RESUME FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);

-- Certificate_Resume_Copy
DROP TABLE IF EXISTS CERTIFICATE_RESUME_COPY;
CREATE TABLE CERTIFICATE_RESUME_COPY (
    CERTIFICATE_RESUME_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESUME_ID INT,
    CERTIFICATE_NAME VARCHAR(3000),
    ACQUISITION_DATE DATE,
    ISSUING_AUTHORITY VARCHAR(3000),
    CONSTRAINT FK_CERT_RESUME_COPY_RESUME FOREIGN KEY (RESUME_ID) REFERENCES RESUME_COPY(RESUME_ID) ON DELETE CASCADE
);

-- MySQL에서는 시퀀스가 AUTO_INCREMENT로 대체되므로 시퀀스 생성 구문 제거
-- Oracle 시퀀스들은 테이블의 AUTO_INCREMENT로 처리됨

SET FOREIGN_KEY_CHECKS = 1; 