-- MySQL Job Group 데이터 삽입 파일
-- Oracle JOB_GROUP_ID_SEQ.NEXTVAL -> MySQL AUTO_INCREMENT (NULL 사용)

INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '기획·전략');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '마케팅·홍보·조사');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '회계·세무·재무');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '인사·노무·HRD');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '총무·법무·사무');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, 'IT개발·데이터');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '디자인');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '영업·판매·무역');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '고객상담·TM');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '구매·자재·물류');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '상품기획·MD');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '운전·운송·배송');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '서비스');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '생산');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '건설·건축');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '의료');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '연구·R&D');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '교육');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '미디어·문화·스포츠');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '금융·보험');
INSERT INTO JOB_GROUP (JOB_GROUP_ID, JOB_GROUP_NAME) VALUES (NULL, '공공·복지');

COMMIT; 