--이력서 더미데이터
-- 1번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE, NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임1의 이력서 1', '닉네임1', '20000101', '010-0000-0001', 'user1@example.com', 14750, '305호', '열정적인 백엔드/서버 개발자입니다.', 1, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 2번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임2의 이력서 1', '닉네임2', '20000102', '010-0000-0002', 'random2@testmail.com', 14751, '306호', '성실한 웹개발자입니다.', 2, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 3번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임3의 이력서 1',  '닉네임3', '20000103', '010-0000-0003', 'data3@demo.net', 14752, '307호', '꼼꼼한 가구 디자이너입니다.', 3, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 4번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임4의 이력서 1',  '닉네임4', '20000104', '010-0000-0004', 'fake4@sample.org', 14753, '308호', '책임감 강한 광고기획자입니다.', 4, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 5번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임5의 이력서 1',  '닉네임5', '20000105', '010-0000-0005', 'dummy5@email.com', 14754, '309호', '창의적인 글로벌 마케터입니다.', 5, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 6번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임6의 이력서 1',  '닉네임6', '20000106', '010-0000-0006', 'info6@mockdata.net', 14755, '310호', '도전적인 마케팅 기획자입니다.', 6, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 7번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임7의 이력서 1',  '닉네임7', '20000107', '010-0000-0007', 'random7@trymail.com', 14756, '311호', '논리적인 웹 개발자입니다.', 7, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 8번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRthDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임8의 이력서 1',  '닉네임8', '20000108', '010-0000-0008', 'demo8@testexample.org', 14757, '312호', '적극적인 모바일 디자이너입니다.', 8, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 9번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임9의 이력서 1',  '닉네임9', '20000109', '010-0000-0009', 'sample9@mailbox.net', 14758, '313호', '열정적인 모바일 마케터입니다.', 9, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 10번
INSERT INTO RESUME (
    RESUME_ID, RESUME_TITLE,   NAME, BIRTHDATE, PHONENUMBER, EMAIL, POSTAL_CODE_ID, ADDRESS, SELF_INTRODUCTION, MEMBER_ID, PROFILE, CREATE_AT, MODIFIED_AT, IS_PUBLIC)
VALUES (RESUME_ID_SEQ.NEXTVAL, '닉네임10의 이력서 1',  '닉네임10', '20000110', '010-0000-0010', 'trial10@dummydata.com', 14759, '314호', '책임감 강한 브랜드 기획자입니다.', 10, 'profile.jpg', SYSDATE, SYSDATE, '1');

-- 이력서 태그(스킬)
-- RESUME_ID: 1 (JOB_GROUP_ID: 6, 백엔드/서버 개발자)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 1, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 1, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 1, 214, SYSDATE, SYSDATE); -- React

-- RESUME_ID: 2 (JOB_GROUP_ID: 6, 웹개발자)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 2, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 2, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 2, 214, SYSDATE, SYSDATE); -- React

-- RESUME_ID: 3 (JOB_GROUP_ID: 7, 가구 디자이너)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 3, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 3, 266, SYSDATE, SYSDATE); -- Illustrator

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 3, 272, SYSDATE, SYSDATE); -- UI 디자인

-- RESUME_ID: 4 (JOB_GROUP_ID: 1, 광고기획자)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 4, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 4, 6, SYSDATE, SYSDATE); -- 데이터분석

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 4, 15, SYSDATE, SYSDATE); -- 신사업기획

-- RESUME_ID: 5 (JOB_GROUP_ID: 2, 글로벌 마케터)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 5, 22, SYSDATE, SYSDATE); -- 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 5, 14, SYSDATE, SYSDATE); -- 시장조사

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 5, 55, SYSDATE, SYSDATE); -- SNS 마케팅

-- RESUME_ID: 6 (JOB_GROUP_ID: 1, 마케팅 기획자)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 6, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 6, 6, SYSDATE, SYSDATE); -- 데이터분석

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 6, 15, SYSDATE, SYSDATE); -- 신사업기획

-- RESUME_ID: 7 (JOB_GROUP_ID: 6, 웹 개발자)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 7, 209, SYSDATE, SYSDATE); -- Java

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 7, 213, SYSDATE, SYSDATE); -- JavaScript

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 7, 214, SYSDATE, SYSDATE); -- React

-- RESUME_ID: 8 (JOB_GROUP_ID: 7, 모바일 디자이너)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 8, 265, SYSDATE, SYSDATE); -- Photoshop

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 8, 266, SYSDATE, SYSDATE); -- Illustrator

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 8, 272, SYSDATE, SYSDATE); -- UI 디자인

-- RESUME_ID: 9 (JOB_GROUP_ID: 2, 모바일 마케터)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 22, SYSDATE, SYSDATE); -- 마케팅

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 14, SYSDATE, SYSDATE); -- 시장조사

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 9, 55, SYSDATE, SYSDATE); -- SNS 마케팅

-- RESUME_ID: 10 (JOB_GROUP_ID: 1, 브랜드 기획자)
INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 10, 1, SYSDATE, SYSDATE); -- 경영관리

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 10, 6, SYSDATE, SYSDATE); -- 데이터분석

INSERT INTO RESUME_TAG (RESUME_TAG_ID, RESUME_ID, TAG_ID, CREATE_AT, MODIFIED_AT)
VALUES (RESUME_TAG_ID_SEQ.NEXTVAL, 10, 15, SYSDATE, SYSDATE); -- 신사업기획

-- 자격증 더미데이터

SELECT * FROM CERTIFICATE;

-- RESUME_ID: 1 (백엔드/서버 개발자, JOB_GROUP_ID: 6)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 1, 177, TO_DATE('2023-01-15', 'YYYY-MM-DD')); -- 정보처리산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 1, 317, TO_DATE('2022-07-20', 'YYYY-MM-DD')); -- 전자계산기기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 1, 962, TO_DATE('2023-05-10', 'YYYY-MM-DD')); -- 전자기사

-- RESUME_ID: 2 (웹개발자, JOB_GROUP_ID: 6)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 2, 177, TO_DATE('2022-11-30', 'YYYY-MM-DD')); -- 정보처리산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 2, 317, TO_DATE('2023-03-22', 'YYYY-MM-DD')); -- 전자계산기기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 2, 962, TO_DATE('2022-09-15', 'YYYY-MM-DD')); -- 전자기사

-- RESUME_ID: 3 (가구 디자이너, JOB_GROUP_ID: 7)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 3, 553, TO_DATE('2023-02-18', 'YYYY-MM-DD')); -- 시각디자인기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 3, 561, TO_DATE('2022-12-05', 'YYYY-MM-DD')); -- 제품디자인기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 3, 319, TO_DATE('2023-04-30', 'YYYY-MM-DD')); -- 실내건축기사

-- RESUME_ID: 4 (광고기획자, JOB_GROUP_ID: 1)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 4, 177, TO_DATE('2022-10-12', 'YYYY-MM-DD')); -- 정보처리산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 4, 301, TO_DATE('2023-01-25', 'YYYY-MM-DD')); -- 산업안전기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 4, 302, TO_DATE('2022-08-17', 'YYYY-MM-DD')); -- 건설안전기사

-- RESUME_ID: 5 (글로벌 마케터, JOB_GROUP_ID: 2)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 5, 656, TO_DATE('2023-02-28', 'YYYY-MM-DD')); -- 텔레마케팅관리사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 5, 914, TO_DATE('2022-11-10', 'YYYY-MM-DD')); -- 영사산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 5, 553, TO_DATE('2023-03-15', 'YYYY-MM-DD')); -- 시각디자인기사

-- RESUME_ID: 6 (마케팅 기획자, JOB_GROUP_ID: 1)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 6, 177, TO_DATE('2022-09-20', 'YYYY-MM-DD')); -- 정보처리산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 6, 301, TO_DATE('2023-04-05', 'YYYY-MM-DD')); -- 산업안전기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 6, 302, TO_DATE('2022-12-22', 'YYYY-MM-DD')); -- 건설안전기사

-- RESUME_ID: 7 (웹 개발자, JOB_GROUP_ID: 6)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 7, 177, TO_DATE('2023-03-10', 'YYYY-MM-DD')); -- 정보처리산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 7, 317, TO_DATE('2022-08-25', 'YYYY-MM-DD')); -- 전자계산기기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 7, 962, TO_DATE('2023-01-30', 'YYYY-MM-DD')); -- 전자기사

-- RESUME_ID: 8 (모바일 디자이너, JOB_GROUP_ID: 7)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 8, 553, TO_DATE('2022-12-15', 'YYYY-MM-DD')); -- 시각디자인기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 8, 561, TO_DATE('2023-02-20', 'YYYY-MM-DD')); -- 제품디자인기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 8, 319, TO_DATE('2022-10-05', 'YYYY-MM-DD')); -- 실내건축기사

-- RESUME_ID: 9 (모바일 마케터, JOB_GROUP_ID: 2)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 9, 656, TO_DATE('2023-01-10', 'YYYY-MM-DD')); -- 텔레마케팅관리사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 9, 914, TO_DATE('2022-11-25', 'YYYY-MM-DD')); -- 영사산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISition_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 9, 553, TO_DATE('2023-04-18', 'YYYY-MM-DD')); -- 시각디자인기사

-- RESUME_ID: 10 (브랜드 기획자, JOB_GROUP_ID: 1)
INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 10, 177, TO_DATE('2022-10-30', 'YYYY-MM-DD')); -- 정보처리산업기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 10, 301, TO_DATE('2023-03-05', 'YYYY-MM-DD')); -- 산업안전기사

INSERT INTO CERTIFICATE_RESUME (CERTIFICATE_RESUME_ID, RESUME_ID, CERTIFICATE_NAME, ACQUISITION_DATE)
VALUES (CERTIFICATE_RESUME_ID_SEQ.NEXTVAL, 10, 302, TO_DATE('2022-12-10', 'YYYY-MM-DD')); -- 건설안전기사

--교육(비학력 이력)
-- RESUME_ID: 1 (백엔드/서버 개발자, JOB_GROUP_ID: 6)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 1, '멀티캠퍼스', '백엔드 개발자 양성과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    'Java, Spring, 데이터베이스 등 백엔드 개발 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 1, '패스트캠퍼스', '클라우드 인프라 실습', TO_DATE('2023-01-10', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    'AWS, Docker, Kubernetes 등 클라우드 환경 구축 실습'
);

-- RESUME_ID: 2 (웹개발자, JOB_GROUP_ID: 6)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 2, '패스트캠퍼스', '프론트엔드 개발자 과정', TO_DATE('2021-07-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    'HTML, CSS, JavaScript, React 등 프론트엔드 개발 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 2, '코드스테이츠', '웹 풀스택 부트캠프', TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'),
    '프론트엔드/백엔드 통합 개발 실무 교육'
);

-- RESUME_ID: 3 (가구 디자이너, JOB_GROUP_ID: 7)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 3, '한국디자인진흥원', '가구디자인 전문가 과정', TO_DATE('2020-06-01', 'YYYY-MM-DD'), TO_DATE('2020-11-30', 'YYYY-MM-DD'),
    '가구 설계, 목공, 디자인 소프트웨어 활용 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 3, '디자인스쿨', '3D 모델링 워크샵', TO_DATE('2021-03-01', 'YYYY-MM-DD'), TO_DATE('2021-05-31', 'YYYY-MM-DD'),
    '3D 모델링, 렌더링, 시뮬레이션 실습'
);

-- RESUME_ID: 4 (광고기획자, JOB_GROUP_ID: 1)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 4, '광고기획 아카데미', '광고기획 전문가 과정', TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'),
    '광고기획, 크리에이티브 전략, 미디어 플래닝 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 4, '마케팅스쿨', '디지털 마케팅 워크숍', TO_DATE('2023-02-01', 'YYYY-MM-DD'), TO_DATE('2023-04-30', 'YYYY-MM-DD'),
    'SNS, 검색광고, 데이터 분석 실습'
);

-- RESUME_ID: 5 (글로벌 마케터, JOB_GROUP_ID: 2)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 5, '글로벌마케팅연구소', '글로벌 마케팅 전문가 과정', TO_DATE('2021-06-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    '글로벌 시장 분석, 브랜드 전략, SNS 마케팅 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 5, '마케팅스쿨', '퍼포먼스 마케팅 워크숍', TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'),
    '구글/페이스북 광고, 데이터 분석 실습'
);

-- RESUME_ID: 6 (마케팅 기획자, JOB_GROUP_ID: 1)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 6, '마케팅기획 아카데미', '마케팅기획 전문가 과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    '마케팅 전략, 데이터 분석, 캠페인 기획 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 6, '마케팅스쿨', '브랜드 전략 워크숍', TO_DATE('2023-01-05', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '브랜드 포지셔닝, 콘셉트 개발 실습'
);

-- RESUME_ID: 7 (웹 개발자, JOB_GROUP_ID: 6)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 7, '코드스테이츠', '웹 개발자 부트캠프', TO_DATE('2021-07-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    'JavaScript, React, Node.js 등 실무 중심 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 7, '멀티캠퍼스', '데이터베이스 실습', TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2022-06-30', 'YYYY-MM-DD'),
    'SQL, NoSQL, 데이터 모델링 실습'
);

-- RESUME_ID: 8 (모바일 디자이너, JOB_GROUP_ID: 7)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 8, '앱디자인 아카데미', '모바일 디자이너 과정', TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'),
    'Figma, Adobe XD, 모바일 앱 프로토타이핑 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 8, '디자인스쿨', 'UI/UX 워크숍', TO_DATE('2023-01-10', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '사용자 경험 설계, 인터랙션 디자인 실습'
);

-- RESUME_ID: 9 (모바일 마케터, JOB_GROUP_ID: 2)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 9, '모바일마케팅 아카데미', '모바일 마케팅 전문가 과정', TO_DATE('2021-06-01', 'YYYY-MM-DD'), TO_DATE('2021-12-31', 'YYYY-MM-DD'),
    '모바일 광고, 퍼포먼스 마케팅, 데이터 분석 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 9, '마케팅스쿨', '모바일 앱 마케팅 워크숍', TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'),
    '앱 광고, ASO, 유저 유입 전략 실습'
);

-- RESUME_ID: 10 (브랜드 기획자, JOB_GROUP_ID: 1)
INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 10, '브랜드기획 아카데미', '브랜드기획 전문가 과정', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-10-31', 'YYYY-MM-DD'),
    '브랜드 전략, 콘셉트 개발, 마케팅 플래닝 실무 교육'
);

INSERT INTO EDUCATION (
    EDU_ID, RESUME_ID, EDU_INSTITUTION, EDU_NAME, START_DATE, END_DATE, CONTENT
)
VALUES (
    EDU_ID_SEQ.NEXTVAL, 10, '마케팅스쿨', '브랜드 커뮤니케이션 워크숍', TO_DATE('2023-01-05', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'),
    '브랜드 메시지, 콘텐츠 기획, 커뮤니케이션 전략 실습'
);

--학력
-- RESUME_ID: 1 (백엔드/서버 개발자, JOB_GROUP_ID: 6)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 1, '고등학교', '서울과학고등학교', TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 1, 'univ4', '서울대학교', TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 2 (웹개발자, JOB_GROUP_ID: 6)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 2, '고등학교', '경기과학고등학교', TO_DATE('2017-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 2, 'univ4', '연세대학교', TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 3 (가구 디자이너, JOB_GROUP_ID: 7)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 3, '고등학교', '예술고등학교', TO_DATE('2016-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 3, 'univ4', '홍익대학교', TO_DATE('2020-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 4 (광고기획자, JOB_GROUP_ID: 1)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 4, '고등학교', '서울고등학교', TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 4, 'univ4', '고려대학교', TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 5 (글로벌 마케터, JOB_GROUP_ID: 2)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 5, '고등학교', '한국외국어고등학교', TO_DATE('2017-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 5, 'univ4', '이화여자대학교', TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 6 (마케팅 기획자, JOB_GROUP_ID: 1)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 6, '고등학교', '서울국제고등학교', TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 6, 'univ4', '서강대학교', TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 7 (웹 개발자, JOB_GROUP_ID: 6)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 7, '고등학교', '경기외국어고등학교', TO_DATE('2017-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 7, 'univ4', '한양대학교', TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 8 (모바일 디자이너, JOB_GROUP_ID: 7)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 8, '고등학교', '예술고등학교', TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 8, 'univ4', '성균관대학교', TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 9 (모바일 마케터, JOB_GROUP_ID: 2)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 9, '고등학교', '한국외국어고등학교', TO_DATE('2017-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 9, 'univ4', '중앙대학교', TO_DATE('2021-02-28', 'YYYY-MM-DD'), '졸업'
);

-- RESUME_ID: 10 (브랜드 기획자, JOB_GROUP_ID: 1)
INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 10, '고등학교', '서울고등학교', TO_DATE('2018-02-28', 'YYYY-MM-DD'), '졸업'
);

INSERT INTO SCHOOL (
    SCHOOL_ID, RESUME_ID, SORTATION, SCHOOL_NAME, YEAR_OF_GRADUATION, STATUS
)
VALUES (
    SCHOOL_ID_SEQ.NEXTVAL, 10, 'univ4', '경희대학교', TO_DATE('2022-02-28', 'YYYY-MM-DD'), '졸업'
);

--경력
-- RESUME_ID: 1 (백엔드/서버 개발자, JOB_GROUP_ID: 6)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 1, '네이버', '클라우드플랫폼개발실', TO_DATE('2022-03-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '백엔드 개발자', 81, 6, 4800, '서버 개발 및 API 설계, 클라우드 환경 구축'
);

-- RESUME_ID: 2 (웹개발자, JOB_GROUP_ID: 6)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 2, '카카오', '웹서비스개발팀', TO_DATE('2021-06-01', 'YYYY-MM-DD'), TO_DATE('2023-04-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4600, 'React 기반 프론트엔드 개발, API 연동'
);

-- RESUME_ID: 3 (가구 디자이너, JOB_GROUP_ID: 7)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 3, '한국가구디자인연구소', '디자인팀', TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2023-06-30', 'YYYY-MM-DD'), '가구 디자이너', 88, 7, 3500, '가구 설계, 3D 모델링, 프로토타입 제작'
);

-- RESUME_ID: 4 (광고기획자, JOB_GROUP_ID: 1)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 4, '제일기획', '광고기획팀', TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '광고기획자', 3, 1, 4200, '광고 캠페인 기획, 크리에이티브 전략 수립'
);

-- RESUME_ID: 5 (글로벌 마케터, JOB_GROUP_ID: 2)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 5, '삼성전자', '글로벌마케팅팀', TO_DATE('2021-08-01', 'YYYY-MM-DD'), TO_DATE('2023-06-30', 'YYYY-MM-DD'), '글로벌 마케터', 19, 2, 5000, '글로벌 시장 분석, 브랜드 전략 수립, 해외 마케팅 실행'
);

-- RESUME_ID: 6 (마케팅 기획자, JOB_GROUP_ID: 1)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 6, '롯데그룹', '마케팅기획팀', TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '마케팅 기획자', 7, 1, 4000, '마케팅 전략 수립, 캠페인 기획, 데이터 분석'
);

-- RESUME_ID: 7 (웹 개발자, JOB_GROUP_ID: 6)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 7, '쿠팡', '웹개발팀', TO_DATE('2021-09-01', 'YYYY-MM-DD'), TO_DATE('2023-06-30', 'YYYY-MM-DD'), '웹 개발자', 85, 6, 4700, '웹 서비스 개발, 프론트엔드/백엔드 통합 개발'
);

-- RESUME_ID: 8 (모바일 디자이너, JOB_GROUP_ID: 7)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 8, '카카오엔터프라이즈', '디자인팀', TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '모바일 디자이너', 100, 7, 3800, '모바일 앱 UI/UX 디자인, 프로토타입 제작'
);

-- RESUME_ID: 9 (모바일 마케터, JOB_GROUP_ID: 2)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 9, '네이버', '모바일마케팅팀', TO_DATE('2021-10-01', 'YYYY-MM-DD'), TO_DATE('2023-06-30', 'YYYY-MM-DD'), '모바일 마케터', 25, 2, 4500, '모바일 광고 캠페인 기획, 퍼포먼스 마케팅'
);

-- RESUME_ID: 10 (브랜드 기획자, JOB_GROUP_ID: 1)
INSERT INTO CAREER (
    CAREER_ID, RESUME_ID, COMPANY_NAME, DEPARTMENT_NAME, HIRE_YM, RESIGN_YM, POSITION, JOB_ID, JOB_GROUP_ID, SALARY, DETAIL
)
VALUES (
    CAREER_ID_SEQ.NEXTVAL, 10, '현대백화점', '브랜드기획팀', TO_DATE('2022-06-01', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), '브랜드 기획자', 10, 1, 4300, '브랜드 전략 수립, 콘셉트 개발, 마케팅 플래닝'
);


COMMIT;