INSERT INTO NOTICE_CATEGORY (NOTICE_CATEGORY_ID,NOTICE_CATEGORY_CONTENT)
VALUES(NOTICE_CATEGORY_ID_SEQ.NEXTVAL, '이벤트');

INSERT INTO NOTICE_CATEGORY (NOTICE_CATEGORY_ID,NOTICE_CATEGORY_CONTENT)
VALUES(NOTICE_CATEGORY_ID_SEQ.NEXTVAL, '일반 공지');

INSERT INTO NOTICE_CATEGORY (NOTICE_CATEGORY_ID,NOTICE_CATEGORY_CONTENT)
VALUES(NOTICE_CATEGORY_ID_SEQ.NEXTVAL, '시스템');

INSERT INTO NOTICE_CATEGORY (NOTICE_CATEGORY_ID,NOTICE_CATEGORY_CONTENT)
VALUES(NOTICE_CATEGORY_ID_SEQ.NEXTVAL, '질의응답');
commit;