CREATE SEQUENCE JOB_GROUP_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE JOB_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE TAG_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE STATE_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE POSTAL_CODE_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE MEMBER_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE COMPANY_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CERTIFICATE_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CAREER_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE EDU_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SCHOOL_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PORTFOLIO_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RESUME_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RM_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RESUME_TAG_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE JOB_POST_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE COMMUNITY_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE COMMUNITY_FILE_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE POST_COMMENT_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE REPLY_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CR_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CM_ID_SEQ
START WITH 1
INCREMENT BY 1;

